//
// Created by jordan on 2022-03-31.
//

#ifndef CAPSTONE_WATER_MONITOR_COMM_SENSOR_PIN_CONFIG_H
#define CAPSTONE_WATER_MONITOR_COMM_SENSOR_PIN_CONFIG_H

#define PIN_EC 0
#define PIN_PH 1
#define PIN_TURBIDITY 2
//#define PIN_TURBIDITY 0
//#define PIN_TURBIDITY 0
//#define PIN_TURBIDITY 0
//#define PIN_TURBIDITY 0

#endif //CAPSTONE_WATER_MONITOR_COMM_SENSOR_PIN_CONFIG_H
